name: forecast
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cool_alert: ^2.0.1
  dio: ^5.1.0
  flutter_screenutil: ^5.7.0
  flutter_riverpod: ^2.3.2
  
  google_fonts: ^4.0.3
  go_router: ^6.5.1
  geolocator: ^9.0.2
  intl: ^0.18.0
  shared_preferences: ^2.0.20
  permission_handler: ^10.2.0
  
  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.12.0

  custom_lint:
  riverpod_lint: ^1.1.5

  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_icons:
  android: "icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg


